name: Greeting
on: push
jobs: 
    greet:
        runs-on: ubuntu-latest
        steps:
            - name: "Greet User"
              run: echo "Hello ${{ github.actor }}"
            - name: "Greet User with Custom Message"
              run: echo "Hello ${{ github.actor }}, welcome to the repository!"